# Add the full path of the images folder in the data_path, train_path, and val_path.
path: '/content/gdrive/My Drive/Colab Notebooks/data'
train: '/content/gdrive/MyDrive/Colab Notebooks/data/images/train'
val: '/content/gdrive/MyDrive/Colab Notebooks/data/images/val'

names:
  0: SRH Logo
  1: Book
  2: Laptop
  3: Monitor
  4: Human
  5: Plant
  6: Flowers
  7: Chair
  8: Desk/Table
  9: Mobile Phones
  10: Tablets
  11: Keyboard
  12: Mouse
  13: Cup
  14: Bottle
